# Site settings
title: Devansh's Portfolio
description: My jekyll portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "devansh-srivastava.github.io" # the base hostname & protocol for your site
author: Devansh Srivastava
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
